# The API Gateway is currently used to expose the Controller API
#   see apigateway/conf/whisk-docker-compose.conf
# Minio is used to mock an object storage ( i.e. S3) that hosts the api-gateway configuration.
# Minio also exposes a web UI to browse the files: http://localhost:9001/minio/api-gateway/
minio:
  image: minio/minio:RELEASE.2018-07-13T00-09-07Z
  command:
    - server
    - /data
  environment:
    - MINIO_ACCESS_KEY=5VCTEQOQ0GR0NV1T67GN
    - MINIO_SECRET_KEY=8MBK5aJTR330V1sohz4n1i7W5Wv/jzahARNHUzi3
  volumes:
    - ~/tmp/openwhisk/minio:/data:rw
  ports:
    - "9001:9000"